import esbuild from 'esbuild';
import process from 'process';
import { readFileSync } from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

function verifyProductionBundle() {
	const bundle = readFileSync('main.js', 'utf8');
	const required = [
		'search-current-note',
		'open-candidates-at-cursor',
		'cmdSearchCurrentNote',
		'Find body link candidates in current note',
		// minified i18n uses \\u escapes for the Japanese command label
		'\\u672C\\u6587\\u30EA\\u30F3\\u30AF\\u5019\\u88DC\\u3092\\u63A2\\u3059',
	];
	for (const needle of required) {
		if (!bundle.includes(needle)) {
			throw new Error(`main.js missing required bundle marker: ${needle}`);
		}
	}
}

if (prod) {
	await context.rebuild();
	verifyProductionBundle();
	process.exit(0);
} else {
	await context.watch();
}
